# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IYPUaxfUDj4YjMibeB8toxCXL56WxSsM
"""



import numpy as np
import time
import hashlib
import matplotlib.pyplot as plt
from copy import deepcopy

# -----------------------------------------------------------------------------
# 1. OPTIMIZED NTT ENGINE
# -----------------------------------------------------------------------------
class LatticeEngine:
    def __init__(self):
        self.n = 256
        self.q = 3329
        self.zeta = 17
        self.zetas = np.array([pow(self.zeta, int('{:07b}'.format(i)[::-1], 2), self.q) for i in range(128)])

    def ntt(self, poly):
        r = poly.copy().astype(int)
        k, level_len = 1, 128
        while level_len >= 2:
            for start in range(0, 256, level_len * 2):
                z = self.zetas[k]; k += 1
                for j in range(start, start + level_len):
                    t = (z * r[j + level_len]) % self.q
                    r[j + level_len] = (r[j] - t) % self.q
                    r[j] = (r[j] + t) % self.q
            level_len //= 2
        return r % self.q

def cbd_sample(seed):
    data = hashlib.shake_128(seed.encode()).digest(64)
    poly = np.zeros(256, dtype=int)
    for i in range(256):
        bits = (data[i // 4] >> ((i % 4) * 2)) & 0x3
        poly[i] = (bits & 0x1) - ((bits >> 1) & 0x1)
    return poly % 3329

# -----------------------------------------------------------------------------
# 2. PROTOCOL LOGIC
# -----------------------------------------------------------------------------
class PCDLProtocol:
    def __init__(self):
        self.eng = LatticeEngine()
        self.q, self.l = 3329, 2
        self.limit, self.window, self.lock_duration = 5, 60, 30
        self.msk_W = "SERVER_MASTER_KEY_001"
        self.Wj = "WEBSITE_TAG_ALPHA"
        self.A = [[np.random.randint(0, self.q, 256) for _ in range(self.l)] for _ in range(self.l)]
        self.DB_W = {}
        self.DB_S = {}

        # Performance tracking
        self.perf_stats = {
            'registration': [],
            'authentication': [],
            'key_rotation': []
        }

    def register(self, un, pwd, track_perf=True):
        t0 = time.perf_counter()
        ti = hashlib.sha256((un + self.Wj).encode()).hexdigest()
        ri_poly = np.random.randint(0, self.q, 256)
        hi = cbd_sample(f"{pwd}{un}{ri_poly.tobytes()}")
        si = cbd_sample(f"{self.msk_W}{ti}{self.Wj}")
        ei = cbd_sample(f"{self.msk_W}{ti}{si.tobytes()}")
        ski_ntt = self.eng.ntt((hi + si) % self.q)
        ei_ntt = self.eng.ntt(ei)
        Bi = []
        for i in range(self.l):
            row = (ei_ntt + sum(self.A[i][j] * ski_ntt for j in range(self.l))) % self.q
            Bi.append(row)
        self.DB_W[ti] = {'un': un, 'ri_poly': ri_poly, 'Bi': Bi}
        self.DB_S[ti] = {'count': 0, 'last_fail': 0, 'lock_until': 0}
        elapsed = time.perf_counter() - t0
        if track_perf:
            self.perf_stats['registration'].append(elapsed * 1000)
        return elapsed, ti

    def authenticate(self, un, pwd_in, track_perf=True):
        t0 = time.perf_counter()
        ti = hashlib.sha256((un + self.Wj).encode()).hexdigest()
        if ti not in self.DB_W: return None, "USER_NOT_FOUND", 0
        state = self.DB_S[ti]
        curr_time = time.time()
        if curr_time < state['lock_until']:
            return None, f"LOCKED_OUT_{int(state['lock_until'] - curr_time)}s", 0

        ri_poly, Bi_stored = self.DB_W[ti]['ri_poly'], self.DB_W[ti]['Bi']
        hi_p = cbd_sample(f"{pwd_in}{un}{ri_poly.tobytes()}")
        si = cbd_sample(f"{self.msk_W}{ti}{self.Wj}")
        ei = cbd_sample(f"{self.msk_W}{ti}{si.tobytes()}")
        ski_p_ntt = self.eng.ntt((hi_p + si) % self.q)
        ei_ntt = self.eng.ntt(ei)
        Bi_calc = [(ei_ntt + sum(self.A[i][j] * ski_p_ntt for j in range(self.l))) % self.q for i in range(self.l)]

        is_valid = all(np.array_equal(Bi_calc[i], Bi_stored[i]) for i in range(self.l))
        elapsed = time.perf_counter() - t0

        if is_valid:
            self.DB_S[ti] = {'count': 0, 'last_fail': 0, 'lock_until': 0}
            if track_perf:
                self.perf_stats['authentication'].append(elapsed * 1000)
            return Bi_calc, "SUCCESS", elapsed
        else:
            if curr_time - state['last_fail'] > self.window: state['count'] = 1
            else: state['count'] += 1
            state['last_fail'] = curr_time
            if state['count'] >= self.limit: state['lock_until'] = curr_time + self.lock_duration
            return Bi_calc, f"FAIL_{state['count']}", elapsed

    def rotate(self, track_perf=True):
        """Perform actual key rotation with proper database updates"""
        t0 = time.perf_counter()
        old_msk = self.msk_W
        new_msk = "NEW_KEY_" + str(time.time())

        # Store old entries before rotation
        old_entries = {}
        for ti, data in self.DB_W.items():
            old_entries[ti] = {
                'un': data['un'],
                'Bi': [b.copy() for b in data['Bi']]
            }

        # Perform actual rotation
        for ti, data in self.DB_W.items():
            si_old = cbd_sample(f"{old_msk}{ti}{self.Wj}")
            ei_old_ntt = self.eng.ntt(cbd_sample(f"{old_msk}{ti}{si_old.tobytes()}"))
            si_new = cbd_sample(f"{new_msk}{ti}{self.Wj}")
            ei_new_ntt = self.eng.ntt(cbd_sample(f"{new_msk}{ti}{si_new.tobytes()}"))
            delta_s_ntt = self.eng.ntt((si_new - si_old) % self.q)

            # Update Bi with proper calculation
            Bi_new = []
            for i in range(self.l):
                # Bi_new = Bi_old - ei_old + delta_s + ei_new (all operations in NTT domain)
                updated = (data['Bi'][i] - ei_old_ntt + sum(self.A[i][j] * delta_s_ntt for j in range(self.l)) + ei_new_ntt) % self.q
                Bi_new.append(updated)

            data['Bi'] = Bi_new

        # Update master key
        self.msk_W = new_msk
        elapsed = time.perf_counter() - t0

        if track_perf:
            self.perf_stats['key_rotation'].append(elapsed * 1000)

        return old_msk, new_msk, old_entries, elapsed

# -----------------------------------------------------------------------------
# 3. GRAPH GENERATOR (Asymptotic Scaling) - NON-BLOCKING
# -----------------------------------------------------------------------------
def plot_asymptotic(phase_name, protocol_instance):
    print(f"\n{'='*60}")
    print(f"Generating Asymptotic Scaling Graph for {phase_name}...")
    print(f"{'='*60}")
    batch_sizes = [1, 10, 50, 100, 250, 500]
    times = []

    # Create a temporary protocol instance for benchmarking to avoid polluting the main DB
    temp_proto = PCDLProtocol()
    temp_proto.A = protocol_instance.A  # Use same A matrix
    temp_proto.msk_W = protocol_instance.msk_W

    for n in batch_sizes:
        t_total = 0
        if phase_name == "Registration":
            for i in range(n):
                dt, _ = temp_proto.register(f"bench_{i}", "pass", track_perf=False)
                t_total += dt
        elif phase_name == "Authentication":
            # Register users first
            for i in range(n):
                temp_proto.register(f"auth_bench_{i}", "pass", track_perf=False)
            # Then authenticate
            for i in range(n):
                _, _, dt = temp_proto.authenticate(f"auth_bench_{i}", "pass", track_perf=False)
                t_total += dt
        elif phase_name == "Key Rotation":
            # Register n users, then rotate them all (time scales with n)
            for i in range(n):
                temp_proto.register(f"rot_bench_{i}", "pass", track_perf=False)
            # Now rotate all n users
            _, _, _, t_total = temp_proto.rotate(track_perf=False)

        times.append(t_total * 1000)

    # Plot
    plt.figure(figsize=(10, 5))
    color_map = {"Registration": "blue", "Authentication": "green", "Key Rotation": "red"}
    plt.plot(batch_sizes, times, marker='s', linestyle='-', linewidth=2,
             markersize=8, color=color_map.get(phase_name, 'blue'))
    plt.title(f"Asymptotic {phase_name} Performance", fontweight='bold', fontsize=14)
    plt.xlabel("Number of Users", fontsize=12)
    plt.ylabel("Total Latency (ms)", fontsize=12)
    plt.grid(True, alpha=0.3)

    # Make plot non-blocking
    plt.tight_layout()
    plt.draw()
    plt.pause(0.001)
    print(f"\n[Graph displayed. You can close it or leave it open.]\n")

# -----------------------------------------------------------------------------
# 4. MAIN INTERACTIVE EXECUTION
# -----------------------------------------------------------------------------
if __name__ == "__main__":
    # Enable interactive mode for matplotlib
    plt.ion()

    proto = PCDLProtocol()

    print("\n" + "="*70)
    print(" "*15 + "PCDL AUTHENTICATION PROTOCOL")
    print("="*70)
    print("\n--- SYSTEM PARAMETERS ---")
    print(f"  Modulus (q)              : {proto.q}")
    print(f"  Polynomial Degree (n)    : {proto.eng.n}")
    print(f"  Matrix Dimension (l)     : {proto.l}")
    print(f"  Failed Attempt Limit     : {proto.limit}")
    print(f"  Time Window for Fails    : {proto.window} seconds")
    print(f"  Account Lock Duration    : {proto.lock_duration} seconds")
    print(f"  Initial Master Key       : {proto.msk_W}")
    print(f"  Website Tag              : {proto.Wj}")
    print("="*70)

    # Mandatory 3-user registration
    print("\n" + "="*70)
    print(" "*20 + "REGISTRATION PHASE")
    print("="*70)
    print("\nPlease register at least 3 users to begin.\n")

    for i in range(3):
        print(f"\n[Registering User {i+1}/3]")
        u = input("  Username: ").strip()
        p = input("  Password: ").strip()

        dt, ti = proto.register(u, p)

        print(f"\n  ✓ Registration Successful!")
        print(f"  → User Identifier (ti): {ti[:16]}...")
        print(f"  → Registration Time: {dt*1000:.4f} ms")
        print(f"  → Database Record:")
        print(f"     • Username: {u}")
        print(f"     • ri_poly (first 5): {proto.DB_W[ti]['ri_poly'][:5]}")
        print(f"     • Bi[0] (first 10): {proto.DB_W[ti]['Bi'][0][:10]}")
        print(f"     • Bi[1] (first 10): {proto.DB_W[ti]['Bi'][1][:10]}")

    # Show Registration Performance Graph
    print("\n" + "-"*70)
    plot_asymptotic("Registration", proto)

    # Main menu loop
    while True:
        print("\n" + "="*70)
        print(" "*25 + "MAIN MENU")
        print("="*70)
        print("  1. Register More Users")
        print("  2. Authenticate User")
        print("  3. Perform Key Rotation")
        print("  4. Exit")
        print("="*70)

        cmd = input("\nSelect Option (1-4): ").strip()

        # =====================================================================
        # OPTION 1: REGISTER MORE USERS
        # =====================================================================
        if cmd == '1':
            print("\n" + "-"*70)
            print(" "*20 + "ADDITIONAL REGISTRATION")
            print("-"*70)
            u = input("  Username: ").strip()
            p = input("  Password: ").strip()

            dt, ti = proto.register(u, p)

            print(f"\n  ✓ Registration Successful!")
            print(f"  → User Identifier (ti): {ti[:16]}...")
            print(f"  → Registration Time: {dt*1000:.4f} ms")
            print(f"  → Database Record:")
            print(f"     • Username: {u}")
            print(f"     • ri_poly (first 5): {proto.DB_W[ti]['ri_poly'][:5]}")
            print(f"     • Bi[0] (first 10): {proto.DB_W[ti]['Bi'][0][:10]}")
            print(f"     • Bi[1] (first 10): {proto.DB_W[ti]['Bi'][1][:10]}")

            plot_asymptotic("Registration", proto)

        # =====================================================================
        # OPTION 2: AUTHENTICATE USER
        # =====================================================================
        elif cmd == '2':
            print("\n" + "-"*70)
            print(" "*22 + "AUTHENTICATION")
            print("-"*70)
            u = input("  Username: ").strip()
            p = input("  Password: ").strip()

            calc_Bi, status, lat = proto.authenticate(u, p)

            # Case 1: User not found
            if status == "USER_NOT_FOUND":
                print(f"\n  ✗ ERROR: Username '{u}' does not exist in the database!")
                print(f"\n  Available users in database:")
                for ti, data in proto.DB_W.items():
                    print(f"     • {data['un']}")

            # Case 2: Account locked
            elif "LOCKED_OUT" in status:
                remaining = status.split("_")[2]
                print(f"\n  🔒 ACCOUNT LOCKED!")
                print(f"  → Too many failed attempts.")
                print(f"  → Account will unlock in: {remaining}")
                print(f"  → Please wait before trying again.")

            # Case 3: Successful authentication
            elif status == "SUCCESS":
                print(f"\n  ✓ AUTHENTICATION SUCCESSFUL!")
                print(f"  → Username: {u}")
                print(f"  → Authentication Time: {lat*1000:.4f} ms")
                print(f"  → Computed Bi matches stored Bi")

                plot_asymptotic("Authentication", proto)

            # Case 4: Wrong password
            else:
                fail_count = int(status.split("_")[1])
                ti = hashlib.sha256((u + proto.Wj).encode()).hexdigest()

                print(f"\n  ✗ WRONG PASSWORD!")
                print(f"  → Failed Attempt Count: {fail_count}/{proto.limit}")

                if fail_count >= proto.limit - 1:
                    print(f"  ⚠ WARNING: One more failed attempt will lock the account!")

                print(f"\n  → Database Entry for '{u}':")
                print(f"     • Stored Bi[0] (first 10): {proto.DB_W[ti]['Bi'][0][:10]}")
                print(f"     • Stored Bi[1] (first 10): {proto.DB_W[ti]['Bi'][1][:10]}")
                print(f"\n  → Your Calculated Bi (with wrong password):")
                print(f"     • Calc Bi[0] (first 10): {calc_Bi[0][:10]}")
                print(f"     • Calc Bi[1] (first 10): {calc_Bi[1][:10]}")
                print(f"\n  → Notice: The calculated values don't match the stored values!")

        # =====================================================================
        # OPTION 3: KEY ROTATION
        # =====================================================================
        elif cmd == '3':
            print("\n" + "-"*70)
            print(" "*22 + "KEY ROTATION")
            print("-"*70)

            old_msk, new_msk, old_entries, lat = proto.rotate()

            print(f"\n  ✓ KEY ROTATION COMPLETED!")
            print(f"  → Rotation Time: {lat*1000:.2f} ms")
            print(f"  → Users Updated: {len(old_entries)}")
            print(f"\n  --- Master Key Update ---")
            print(f"  Old Master Key: {old_msk}")
            print(f"  New Master Key: {new_msk}")

            print(f"\n  --- Database Entries Update ---")
            for ti, old_data in old_entries.items():
                new_data = proto.DB_W[ti]
                print(f"\n  User: {old_data['un']}")
                print(f"  ┌─ Before Rotation (with old key: {old_msk}):")
                print(f"  │  • Bi[0] (first 10): {old_data['Bi'][0][:10]}")
                print(f"  │  • Bi[1] (first 10): {old_data['Bi'][1][:10]}")
                print(f"  └─ After Rotation (with new key: {new_msk[:30]}...):")
                print(f"     • Bi[0] (first 10): {new_data['Bi'][0][:10]}")
                print(f"     • Bi[1] (first 10): {new_data['Bi'][1][:10]}")

            plot_asymptotic("Key Rotation", proto)

        # =====================================================================
        # OPTION 4: EXIT
        # =====================================================================
        elif cmd == '4':
            print("\n" + "="*70)
            print(" "*20 + "PERFORMANCE SUMMARY")
            print("="*70)

            # Calculate statistics
            stats_table = []

            if proto.perf_stats['registration']:
                reg_times = proto.perf_stats['registration']
                stats_table.append([
                    'Registration',
                    len(reg_times),
                    f"{np.mean(reg_times):.4f}",
                    f"{np.min(reg_times):.4f}",
                    f"{np.max(reg_times):.4f}",
                    f"{np.std(reg_times):.4f}"
                ])

            if proto.perf_stats['authentication']:
                auth_times = proto.perf_stats['authentication']
                stats_table.append([
                    'Authentication',
                    len(auth_times),
                    f"{np.mean(auth_times):.4f}",
                    f"{np.min(auth_times):.4f}",
                    f"{np.max(auth_times):.4f}",
                    f"{np.std(auth_times):.4f}"
                ])

            if proto.perf_stats['key_rotation']:
                rot_times = proto.perf_stats['key_rotation']
                stats_table.append([
                    'Key Rotation',
                    len(rot_times),
                    f"{np.mean(rot_times):.4f}",
                    f"{np.min(rot_times):.4f}",
                    f"{np.max(rot_times):.4f}",
                    f"{np.std(rot_times):.4f}"
                ])

            # Display table
            if stats_table:
                print("\n┌" + "─"*68 + "┐")
                print("│ {:^18} │ {:^6} │ {:^10} │ {:^10} │ {:^10} │ {:^7} │".format(
                    "Protocol", "Count", "Avg (ms)", "Min (ms)", "Max (ms)", "Std Dev"))
                print("├" + "─"*68 + "┤")

                for row in stats_table:
                    print("│ {:<18} │ {:>6} │ {:>10} │ {:>10} │ {:>10} │ {:>7} │".format(*row))

                print("└" + "─"*68 + "┘")

                print("\nTotal Operations Performed:")
                print(f"  • Registrations: {len(proto.perf_stats['registration'])}")
                print(f"  • Authentications: {len(proto.perf_stats['authentication'])}")
                print(f"  • Key Rotations: {len(proto.perf_stats['key_rotation'])}")
            else:
                print("\nNo performance data collected.")

            print("\n" + "="*70)
            print(" "*25 + "Exiting Protocol")
            print("="*70)
            plt.close('all')
            break

        else:
            print("\n  ✗ Invalid option. Please select 1-4.")